### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by yasinx7** [htr-tech/haxorbd#6]
![Screenshot_20220116_205345](https://user-images.githubusercontent.com/77639060/149665143-002f505f-5d73-4837-9914-469c0cfb8e59.jpg)

**Comment by htr-tech** [comment]
turn on vpn until the login appears

**Comment by htr-tech** [comment]
then turn the vpn off

**Comment by Abcdefgh2245** [comment]
Vai ki ata

**Comment by yasinx7** [comment]
> turn on vpn until the login appears

Thanks it's worked
